# Generated by Django 3.2 on 2022-12-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='dob',
            field=models.DateField(auto_now=True, max_length=8),
        ),
    ]
